// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pardis.Infrastructure;

#nullable disable

namespace Pardis.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251127145939_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Pardis.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CoursesCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            CoursesCount = 3,
                            CreatedAt = new DateTime(2025, 11, 27, 14, 59, 37, 608, DateTimeKind.Utc).AddTicks(9028),
                            CreatedById = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            IsActive = true,
                            Slug = "programming",
                            Title = "برنامه نویسی",
                            UpdatedAt = new DateTime(2025, 11, 27, 14, 59, 37, 608, DateTimeKind.Utc).AddTicks(9030)
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            CoursesCount = 2,
                            CreatedAt = new DateTime(2025, 11, 27, 14, 59, 37, 608, DateTimeKind.Utc).AddTicks(9964),
                            CreatedById = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            IsActive = true,
                            ParentId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Slug = "web-development",
                            Title = "توسعه وب",
                            UpdatedAt = new DateTime(2025, 11, 27, 14, 59, 37, 608, DateTimeKind.Utc).AddTicks(9965)
                        },
                        new
                        {
                            Id = new Guid("b3333333-3333-3333-3333-333333333333"),
                            CoursesCount = 1,
                            CreatedAt = new DateTime(2025, 11, 27, 14, 59, 37, 608, DateTimeKind.Utc).AddTicks(9971),
                            CreatedById = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            IsActive = true,
                            ParentId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Slug = "mobile-development",
                            Title = "برنامه نویسی موبایل",
                            UpdatedAt = new DateTime(2025, 11, 27, 14, 59, 37, 608, DateTimeKind.Utc).AddTicks(9971)
                        },
                        new
                        {
                            Id = new Guid("b4444444-4444-4444-4444-444444444444"),
                            CoursesCount = 0,
                            CreatedAt = new DateTime(2025, 11, 27, 14, 59, 37, 608, DateTimeKind.Utc).AddTicks(9974),
                            CreatedById = "2c4e6097-f570-4927-b2f7-5f65d1373555",
                            IsActive = true,
                            Slug = "art-design",
                            Title = "هنر و طراحی",
                            UpdatedAt = new DateTime(2025, 11, 27, 14, 59, 37, 608, DateTimeKind.Utc).AddTicks(9975)
                        });
                });

            modelBuilder.Entity("Pardis.Domain.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            CategoryId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 9, 27, 14, 59, 37, 609, DateTimeKind.Utc).AddTicks(2747),
                            Description = "آموزش پروژه محور ساخت سایت فروشگاهی با معماری Clean",
                            InstructorId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            IsDeleted = false,
                            Price = 2500000L,
                            Slug = "aspnet-core-8-comprehensive",
                            Status = 1,
                            Title = "دوره جامع ASP.NET Core 8",
                            UpdatedAt = new DateTime(2025, 11, 27, 14, 59, 37, 609, DateTimeKind.Utc).AddTicks(2848)
                        },
                        new
                        {
                            Id = new Guid("c2222222-2222-2222-2222-222222222222"),
                            CategoryId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 10, 27, 14, 59, 37, 609, DateTimeKind.Utc).AddTicks(3417),
                            Description = "از مقدماتی تا پیشرفته همراه با هوک ها",
                            InstructorId = "2c4e6097-f570-4927-b2f7-5f65d1373555",
                            IsDeleted = false,
                            Price = 1800000L,
                            Slug = "react-nextjs-mastery",
                            Status = 1,
                            Title = "متخصص React و Next.js",
                            UpdatedAt = new DateTime(2025, 11, 27, 14, 59, 37, 609, DateTimeKind.Utc).AddTicks(3421)
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333333"),
                            CategoryId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2025, 11, 27, 14, 59, 37, 609, DateTimeKind.Utc).AddTicks(3425),
                            Description = "ساخت اپلیکیشن های اندروید و iOS با یک کد",
                            InstructorId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            IsDeleted = false,
                            Price = 3000000L,
                            Slug = "flutter-zero-to-hero",
                            Status = 0,
                            Title = "فلاتر: از صفر تا انتشار در مارکت",
                            UpdatedAt = new DateTime(2025, 11, 27, 14, 59, 37, 609, DateTimeKind.Utc).AddTicks(3425)
                        });
                });

            modelBuilder.Entity("Pardis.Domain.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "df887a21-02c9-4f5f-81bd-61d375ef37ee",
                            CreatedAt = new DateTime(2025, 11, 27, 14, 59, 37, 521, DateTimeKind.Utc).AddTicks(9967),
                            Email = "admin@pardis.com",
                            EmailConfirmed = true,
                            FullName = "مدیر سیستم",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@PARDIS.COM",
                            NormalizedUserName = "ADMIN@PARDIS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAED40izAXJyj5r2zn0R52ivfGCmQ4pQehST09P5vplvA8Z6da+4d9Upc4FKE3+yUxGA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "610e0848-0cb6-4081-8b24-80ddb8aca59e",
                            TwoFactorEnabled = false,
                            UserName = "admin@pardis.com"
                        },
                        new
                        {
                            Id = "2c4e6097-f570-4927-b2f7-5f65d1373555",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e9b16540-ee16-4615-9f7a-f9e4e71dbe26",
                            CreatedAt = new DateTime(2025, 11, 27, 14, 59, 37, 568, DateTimeKind.Utc).AddTicks(204),
                            Email = "sara@pardis.com",
                            EmailConfirmed = true,
                            FullName = "سارا مدرس",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SARA@PARDIS.COM",
                            NormalizedUserName = "SARA@PARDIS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEG/MT37D3fC8LSwZV5reS/YUVPRcQQzjzVWEhwez09HMLpJdIv8xTltI92FWP73gsg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e3e55c43-1464-4f40-8f88-6b096c2ad4d9",
                            TwoFactorEnabled = false,
                            UserName = "sara@pardis.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Pardis.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Pardis.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pardis.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Pardis.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pardis.Domain.Categories.Category", b =>
                {
                    b.HasOne("Pardis.Domain.Users.User", "Creator")
                        .WithMany("CreatedCategories")
                        .HasForeignKey("CreatedById");

                    b.HasOne("Pardis.Domain.Categories.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.OwnsOne("Pardis.Domain.Seo.SeoMetadata", "Seo", b1 =>
                        {
                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CanonicalUrl")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MetaDescription")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MetaTitle")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("NoFollow")
                                .HasColumnType("bit");

                            b1.Property<bool>("NoIndex")
                                .HasColumnType("bit");

                            b1.HasKey("CategoryId");

                            b1.ToTable("Categories");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");

                            b1.HasData(
                                new
                                {
                                    CategoryId = new Guid("b1111111-1111-1111-1111-111111111111"),
                                    MetaDescription = "جامع ترین دوره ها",
                                    MetaTitle = "آموزش برنامه نویسی",
                                    NoFollow = false,
                                    NoIndex = false
                                },
                                new
                                {
                                    CategoryId = new Guid("b2222222-2222-2222-2222-222222222222"),
                                    MetaDescription = "ASP.NET و React",
                                    MetaTitle = "آموزش طراحی سایت",
                                    NoFollow = false,
                                    NoIndex = false
                                },
                                new
                                {
                                    CategoryId = new Guid("b3333333-3333-3333-3333-333333333333"),
                                    MetaDescription = "فلاتر و کاتلین",
                                    MetaTitle = "آموزش موبایل",
                                    NoFollow = false,
                                    NoIndex = false
                                },
                                new
                                {
                                    CategoryId = new Guid("b4444444-4444-4444-4444-444444444444"),
                                    MetaDescription = "نقاشی و طراحی",
                                    MetaTitle = "آموزش هنر",
                                    NoFollow = false,
                                    NoIndex = false
                                });
                        });

                    b.Navigation("Creator");

                    b.Navigation("Parent");

                    b.Navigation("Seo")
                        .IsRequired();
                });

            modelBuilder.Entity("Pardis.Domain.Courses.Course", b =>
                {
                    b.HasOne("Pardis.Domain.Categories.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pardis.Domain.Users.User", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Pardis.Domain.Seo.SeoMetadata", "Seo", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CanonicalUrl")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MetaDescription")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MetaTitle")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("NoFollow")
                                .HasColumnType("bit");

                            b1.Property<bool>("NoIndex")
                                .HasColumnType("bit");

                            b1.HasKey("CourseId");

                            b1.ToTable("Courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");

                            b1.HasData(
                                new
                                {
                                    CourseId = new Guid("c1111111-1111-1111-1111-111111111111"),
                                    MetaDescription = "بهترین دوره بک اند",
                                    MetaTitle = "دوره ASP.NET Core",
                                    NoFollow = false,
                                    NoIndex = false
                                },
                                new
                                {
                                    CourseId = new Guid("c2222222-2222-2222-2222-222222222222"),
                                    MetaDescription = "آموزش فرانت اند",
                                    MetaTitle = "دوره React",
                                    NoFollow = false,
                                    NoIndex = false
                                },
                                new
                                {
                                    CourseId = new Guid("c3333333-3333-3333-3333-333333333333"),
                                    MetaDescription = "برنامه نویسی موبایل",
                                    MetaTitle = "دوره Flutter",
                                    NoFollow = false,
                                    NoIndex = true
                                });
                        });

                    b.Navigation("Category");

                    b.Navigation("Instructor");

                    b.Navigation("Seo")
                        .IsRequired();
                });

            modelBuilder.Entity("Pardis.Domain.Categories.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Pardis.Domain.Users.User", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("CreatedCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
