// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pardis.Infrastructure;

#nullable disable

namespace Pardis.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251127181350_AddOrganizationalRoles")]
    partial class AddOrganizationalRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentityRole");

                    b.HasData(
                        new
                        {
                            Id = "00edafe3-b047-5980-d0fa-da10f400c1e5",
                            ConcurrencyStamp = "fecf871f-83ad-49f6-afc2-c65793b96cc6",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "3cbe94ae-32d5-4ace-0258-84819eb08c98",
                            ConcurrencyStamp = "c350b5a5-993a-4b02-a9be-39c471888b83",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "c6416b99-2025-9adc-1585-61825436c565",
                            ConcurrencyStamp = "ff367eff-9198-4a06-840d-a7a7b38c64b5",
                            Name = "FinancialManager",
                            NormalizedName = "FINANCIALMANAGER"
                        },
                        new
                        {
                            Id = "c8bcf807-3aac-0148-1c67-c0d0f77f07d0",
                            ConcurrencyStamp = "8ef0acda-511b-4533-9128-fc7fe421564d",
                            Name = "Instructor",
                            NormalizedName = "INSTRUCTOR"
                        },
                        new
                        {
                            Id = "c9a1c0f5-4c38-252e-e79b-a1abf5d9a037",
                            ConcurrencyStamp = "79abfb6f-36ec-4f9f-854e-98ba9c08aa19",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = "19d55d6e-3f29-3955-a536-31adce03c0b2",
                            ConcurrencyStamp = "9019f580-19a1-4d07-9283-becd059eb166",
                            Name = "ITManager",
                            NormalizedName = "ITMANAGER"
                        },
                        new
                        {
                            Id = "a74fab8d-2d81-7ae5-1871-0538e4088d26",
                            ConcurrencyStamp = "3b305c22-af9e-4022-bab2-983dfcfa2aff",
                            Name = "MarketingManager",
                            NormalizedName = "MARKETINGMANAGER"
                        },
                        new
                        {
                            Id = "660905f4-03e4-eec3-85e1-735cab1308e8",
                            ConcurrencyStamp = "5b6c337d-ffd7-4ef3-bf85-236c04924dc9",
                            Name = "EducationManager",
                            NormalizedName = "EDUCATIONMANAGER"
                        },
                        new
                        {
                            Id = "2c131675-e751-e65c-5534-cbdcc96c2c45",
                            ConcurrencyStamp = "81c6a805-b3e4-47cd-bd46-f5c77af5effc",
                            Name = "Accountant",
                            NormalizedName = "ACCOUNTANT"
                        },
                        new
                        {
                            Id = "ae0ec1fc-3a9e-6b14-e4b7-b1f23adaf800",
                            ConcurrencyStamp = "6b9af964-9a80-49fa-94bd-8954ca895155",
                            Name = "GeneralManager",
                            NormalizedName = "GENERALMANAGER"
                        },
                        new
                        {
                            Id = "ce39a444-665b-6b66-23aa-fede411c6fc0",
                            ConcurrencyStamp = "81c9b7ae-b69f-4e95-be2b-da6617a37702",
                            Name = "DepartmentManager",
                            NormalizedName = "DEPARTMENTMANAGER"
                        },
                        new
                        {
                            Id = "6ddc93a3-048a-da24-faab-ed198c8d1e5a",
                            ConcurrencyStamp = "f822f812-4582-42bc-9ac5-cccb66361df2",
                            Name = "CourseSupport",
                            NormalizedName = "COURSESUPPORT"
                        },
                        new
                        {
                            Id = "6cc9d6b9-06ae-ceb2-5ff7-bec172fc7cb7",
                            ConcurrencyStamp = "9d1d40da-c32d-45bb-b313-93ee1272deec",
                            Name = "Marketer",
                            NormalizedName = "MARKETER"
                        },
                        new
                        {
                            Id = "bdbda483-9107-7444-1c63-b8f8b8f56aff",
                            ConcurrencyStamp = "f97613f2-a891-4867-a375-9d46e90b675f",
                            Name = "InternalManager",
                            NormalizedName = "INTERNALMANAGER"
                        },
                        new
                        {
                            Id = "52c145a7-4624-5c8d-f270-e6a048c2ca71",
                            ConcurrencyStamp = "2c2420be-15b1-4f1f-9a1e-b2e0b91c336c",
                            Name = "EducationExpert",
                            NormalizedName = "EDUCATIONEXPERT"
                        },
                        new
                        {
                            Id = "9dfe9b8f-4513-7c23-b3b2-b205864da075",
                            ConcurrencyStamp = "7f1cc765-1dcc-47f0-9006-b1dc98c10906",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Pardis.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CoursesCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1111111-1111-1111-1111-111111111111"),
                            CoursesCount = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            IsActive = true,
                            Slug = "programming",
                            Title = "برنامه نویسی",
                            UpdatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b2222222-2222-2222-2222-222222222222"),
                            CoursesCount = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            IsActive = true,
                            ParentId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Slug = "web-development",
                            Title = "توسعه وب",
                            UpdatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b3333333-3333-3333-3333-333333333333"),
                            CoursesCount = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            IsActive = true,
                            ParentId = new Guid("b1111111-1111-1111-1111-111111111111"),
                            Slug = "mobile-development",
                            Title = "برنامه نویسی موبایل",
                            UpdatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("b4444444-4444-4444-4444-444444444444"),
                            CoursesCount = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            CreatedById = "2c4e6097-f570-4927-b2f7-5f65d1373555",
                            IsActive = true,
                            Slug = "art-design",
                            Title = "هنر و طراحی",
                            UpdatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Pardis.Domain.Courses.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstructorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1111111-1111-1111-1111-111111111111"),
                            CategoryId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "آموزش پروژه محور",
                            InstructorId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            IsDeleted = false,
                            Price = 2500000L,
                            Slug = "aspnet-core-8-comprehensive",
                            Status = 1,
                            Title = "دوره جامع ASP.NET Core 8",
                            UpdatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c2222222-2222-2222-2222-222222222222"),
                            CategoryId = new Guid("b2222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "از مقدماتی تا پیشرفته",
                            InstructorId = "2c4e6097-f570-4927-b2f7-5f65d1373555",
                            IsDeleted = false,
                            Price = 1800000L,
                            Slug = "react-nextjs-mastery",
                            Status = 1,
                            Title = "متخصص React و Next.js",
                            UpdatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("c3333333-3333-3333-3333-333333333333"),
                            CategoryId = new Guid("b3333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Description = "ساخت اپلیکیشن",
                            InstructorId = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            IsDeleted = false,
                            Price = 3000000L,
                            Slug = "flutter-zero-to-hero",
                            Status = 0,
                            Title = "فلاتر: از صفر تا صد",
                            UpdatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Pardis.Domain.Users.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Pardis.Domain.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5117a984-3399-43f4-b7c7-5b7cb11ba558",
                            CreatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@pardis.com",
                            EmailConfirmed = true,
                            FullName = "مدیر سیستم",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@PARDIS.COM",
                            NormalizedUserName = "ADMIN@PARDIS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEMorXuBKMB6vasAAZABvhB3SIES0dXY7iiP7xdzXi3i7D+7B028qySvv/fnxZo9bcA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8e445865-a24d-4543-a6c6-9443d048cdb9",
                            TwoFactorEnabled = false,
                            UserName = "admin@pardis.com"
                        },
                        new
                        {
                            Id = "2c4e6097-f570-4927-b2f7-5f65d1373555",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "464043b1-7372-46c2-9a7b-76026724be1c",
                            CreatedAt = new DateTime(2024, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sara@pardis.com",
                            EmailConfirmed = true,
                            FullName = "سارا مدرس",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "SARA@PARDIS.COM",
                            NormalizedUserName = "SARA@PARDIS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGBMBFNzlCpeebHsq8zfLA0fIYx9fDlL5RBCA3manWLkmlEh0K7kqwP0s5lVRkeX+g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2c4e6097-f570-4927-b2f7-5f65d1373555",
                            TwoFactorEnabled = false,
                            UserName = "sara@pardis.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Pardis.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Pardis.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Pardis.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Pardis.Domain.Users.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pardis.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Pardis.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pardis.Domain.Categories.Category", b =>
                {
                    b.HasOne("Pardis.Domain.Users.User", "Creator")
                        .WithMany("CreatedCategories")
                        .HasForeignKey("CreatedById");

                    b.HasOne("Pardis.Domain.Categories.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.OwnsOne("Pardis.Domain.Seo.SeoMetadata", "Seo", b1 =>
                        {
                            b1.Property<Guid>("CategoryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CanonicalUrl")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MetaDescription")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MetaTitle")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("NoFollow")
                                .HasColumnType("bit");

                            b1.Property<bool>("NoIndex")
                                .HasColumnType("bit");

                            b1.HasKey("CategoryId");

                            b1.ToTable("Categories");

                            b1.WithOwner()
                                .HasForeignKey("CategoryId");

                            b1.HasData(
                                new
                                {
                                    CategoryId = new Guid("b1111111-1111-1111-1111-111111111111"),
                                    MetaDescription = "جامع ترین دوره ها",
                                    MetaTitle = "آموزش برنامه نویسی",
                                    NoFollow = false,
                                    NoIndex = false
                                },
                                new
                                {
                                    CategoryId = new Guid("b2222222-2222-2222-2222-222222222222"),
                                    MetaDescription = "ASP.NET و React",
                                    MetaTitle = "آموزش طراحی سایت",
                                    NoFollow = false,
                                    NoIndex = false
                                },
                                new
                                {
                                    CategoryId = new Guid("b3333333-3333-3333-3333-333333333333"),
                                    MetaDescription = "فلاتر و کاتلین",
                                    MetaTitle = "آموزش موبایل",
                                    NoFollow = false,
                                    NoIndex = false
                                },
                                new
                                {
                                    CategoryId = new Guid("b4444444-4444-4444-4444-444444444444"),
                                    MetaDescription = "نقاشی و طراحی",
                                    MetaTitle = "آموزش هنر",
                                    NoFollow = false,
                                    NoIndex = false
                                });
                        });

                    b.Navigation("Creator");

                    b.Navigation("Parent");

                    b.Navigation("Seo")
                        .IsRequired();
                });

            modelBuilder.Entity("Pardis.Domain.Courses.Course", b =>
                {
                    b.HasOne("Pardis.Domain.Categories.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pardis.Domain.Users.User", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Pardis.Domain.Seo.SeoMetadata", "Seo", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CanonicalUrl")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MetaDescription")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MetaTitle")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("NoFollow")
                                .HasColumnType("bit");

                            b1.Property<bool>("NoIndex")
                                .HasColumnType("bit");

                            b1.HasKey("CourseId");

                            b1.ToTable("Courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");

                            b1.HasData(
                                new
                                {
                                    CourseId = new Guid("c1111111-1111-1111-1111-111111111111"),
                                    MetaDescription = "بهترین دوره بک اند",
                                    MetaTitle = "دوره ASP.NET Core",
                                    NoFollow = false,
                                    NoIndex = false
                                },
                                new
                                {
                                    CourseId = new Guid("c2222222-2222-2222-2222-222222222222"),
                                    MetaDescription = "آموزش فرانت اند",
                                    MetaTitle = "دوره React",
                                    NoFollow = false,
                                    NoIndex = false
                                },
                                new
                                {
                                    CourseId = new Guid("c3333333-3333-3333-3333-333333333333"),
                                    MetaDescription = "برنامه نویسی موبایل",
                                    MetaTitle = "دوره Flutter",
                                    NoFollow = false,
                                    NoIndex = true
                                });
                        });

                    b.Navigation("Category");

                    b.Navigation("Instructor");

                    b.Navigation("Seo")
                        .IsRequired();
                });

            modelBuilder.Entity("Pardis.Domain.Categories.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Courses");
                });

            modelBuilder.Entity("Pardis.Domain.Users.User", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("CreatedCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
